### ISSUE TITLE
No Filter Option for Minted (TPos)-Entries in Transaction-Tab

### ISSUE THREAD

**Issue by LeeeNux** [X9Developers/XSN#103]
Current Behavior:

Currently there is no Filter-Option for Minted (TPos) - Stakes .... if i choose the Option 'Minted' it seems that only normal Stakes genrated by online wallets are shown. I remember this was different in early versions of the wallet.

Expected Bahavior:

New Filter-Option also for Minted (TPos) ... Alternative: Filter-Option 'Minted' also lists TPos-Stakes

Reproducable

Yes

**Comment by AndriiDiachuk** [comment]
closed in PL #105
