### ISSUE TITLE
sendtoaddress number of splits option is missing, alternative or automatic split needed

### ISSUE THREAD

**Issue by eloygil** [X9Developers/XSN#104]
We have observed that in the latest versions of the wallet the _sendtoaddress_ command doesn't have the _number of splits_ option anymore, so we expected an automatic way of splitting.

We expected to find a different way to split while sending or an automatic split. 

We're using a pre-compiled linux v1.0.14 but it should affect all versions from now.

**Comment by AndriiDiachuk** [comment]
Closed in bugfix #102
