### ISSUE TITLE
Links should redirect to XSN-Git and official xsncoin.io-Site in About-Dialog 

### ISSUE THREAD

**Issue by LeeeNux** [X9Developers/XSN#109]
XSN Core Version v1.0.15.0-fe912b5f1 (64-Bit)

Copyright (C) 2009-2018 The XSN Core developers

Please contribute if you find XSN Core useful. Visit **https://xsncore.org** for further information about the software.
The source code is available from **https://github.com/xsn/xsn**.

Dies ist experimentelle Software.
Distributed under the MIT software license, see the accompanying file COPYING or https://opensource.org/licenses/MIT

This product includes software developed by the OpenSSL Project for use in the OpenSSL Toolkit https://www.openssl.org and cryptographic software written by Eric Young and UPnP software written by Thomas Bernard.

This software is experimental, use at your own risk. XSN-core, contributing developers, and any affiliates take no responsibility for the technical functionalities or the lack thereof

**Comment by stakoholic** [comment]
the old/dead links are also in the README.md and pls replace the old logo in the wallet with the new
