### ISSUE TITLE
Masternode-Counter doesn't decrease

### ISSUE THREAD

**Issue by LeeeNux** [X9Developers/XSN#112]
![image](https://user-images.githubusercontent.com/25117481/45583110-512bfd80-b8bc-11e8-88da-234deb76b09d.png)

**Comment by LeeeNux** [comment]
it seems like the masternodecount shows always the ath of nodes .. and not the current situation. also the masternode list shows a list ... that doesn't change.

![bildschirmfoto_2018-09-15_07-52-59](https://user-images.githubusercontent.com/25117481/45583152-e4fdc980-b8bc-11e8-986f-e9f1faf6e41b.png)

**Comment by bwang22** [comment]
Fixed in newest wallet
