### ISSUE TITLE
Signmessage command does not work with Segwit address

### ISSUE THREAD

**Issue by Kuosumi** [X9Developers/XSN#119]
Signmessage in XSN wallet, should sign the address and verify address owner is true. 

This works for legacy addresses however; when using SegWit addresses, it returns the following:

Address does not refer to key (code -3)

Address was unable to be signed as expected with that command. 

Yes, tried on two different wallets - same issue. 

Wallet version 1.0.17

Windows

**Comment by bwang22** [comment]
The address is a p2sh address, it doesn't have an associated public or private key to sign and verify messages with. The underlying script has a private key associated with it, but not the address itself.

https://github.com/bitcoin/bitcoin/issues/10542
