### ISSUE TITLE
tpos/tposutils.cpp:231:28: error: ‘accumulate’ is not a member of ‘std’

### ISSUE THREAD

**Issue by LeeeNux** [X9Developers/XSN#2]
when building from "git clone https://github.com/X9Developers/XSN.git" i get following compile error:

tpos/tposutils.cpp:231:28: error: ‘accumulate’ is not a member of ‘std’
     merchantPayment = std::accumulate(std::begin(coinstake.vout) + 2, std::end(coinstake.vout), CAmount(0), [scriptMerchantPubKey](CAmount accum, const CTxOut &txOut) { ...

**Comment by durkmurder** [comment]
Fixed in commit [943224ad3d2fce3a2a512730501f70314fcbaf78](https://github.com/X9Developers/XSN/commit/943224ad3d2fce3a2a512730501f70314fcbaf78)
