### ISSUE TITLE
XSN Core-Wallet dumps core on Linux

### ISSUE THREAD

**Issue by iSnow** [X9Developers/XSN#26]
xsn-qt dumps core frequently but irregularly on my Debian 16.4.1 box. 

There is not obvious issue visible in the debug.log. The last entry is always `XsnMiner -- Failed to find a coinstake`, but those entries are frequent without crash. It could be related to either the screen lock engaging or happen directly after logging in.

uname -a: `Linux zbox 4.10.0-38-generic #42~16.04.1-Ubuntu SMP Tue Oct 10 16:32:20 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

I don't know where to look for the core dump, please tell me which files I should attach.

**Comment by bwang22** [comment]
`XsnMiner -- Failed to find a coinstake` means your wallet is staking but failed to mint a block. The dump is debug.log
