### ISSUE TITLE
test/coins_tests.cpp: no matching function

### ISSUE THREAD

**Issue by LeeNuxBerlin** [X9Developers/XSN#3]
when building from "git clone https://github.com/X9Developers/XSN.git" i get following compile error:

test/coins_tests.cpp:377:86: error: no matching function for call to ‘Coin::Coin(__gnu_cxx::__alloc_traits<std::allocator<CTxOut> >::value_type&, unsigned int&, bool)’

test/coins_tests.cpp:724:73: error: no matching function for call to ‘Coin::Coin(std::remove_reference<CTxOut&>::type, int, bool&)’

**Comment by bwang22** [comment]
Did you follow the [guide here](https://github.com/X9Developers/XSN/blob/master/doc/build-unix.md)

**Comment by LeeeNux** [comment]
i followed instructions here: https://github.com/X9Developers/XSN/blob/master/doc/build-unix.md

**Comment by durkmurder** [comment]
I will fix tests soon, for time being you can do next thing: ./configure --disable-tests.

**Comment by LeeeNux** [comment]
./configure --disable-tests did the trick ... thx

**Comment by bwang22** [comment]
Ty @durkmurder test is a high priority.
