### ISSUE TITLE
Sending Coins to myself shows transaction fee instead of amount to send

### ISSUE THREAD

**Issue by LeeeNux** [X9Developers/XSN#31]
Example:

![image](https://user-images.githubusercontent.com/25117481/38442528-e28ece5e-39e8-11e8-9a3d-2692737f13ff.png)

![image](https://user-images.githubusercontent.com/25117481/38442582-06cca67e-39e9-11e8-94d2-abb694d9fbf9.png)

Somewhere here?

https://github.com/X9Developers/XSN/blob/master/src/qt/transactionrecord.cpp

**Comment by durkmurder** [comment]
This is standard behavior for most BTC wallets, not sure if we need to change that. You can always see details when you open the transaction.
