### ISSUE TITLE
Genesis block contains a transaction that can't be retrieved

### ISSUE THREAD

**Issue by AlexITC** [X9Developers/XSN#32]
Is there any particular reason why this is not found? The current block explorer is not displaying the genesis block due to this.
 
### 1. Find the genesis block
```
bin/xsn-cli getblockhash 0
00000c822abdbb23e28f79a49d29b41429737c6c7e15df40d1b1f1b35907ae34
```

### 2. Get the block details
```
bin/xsn-cli getblock 00000c822abdbb23e28f79a49d29b41429737c6c7e15df40d1b1f1b35907ae34
{
  ...
  "tx": [
    "922ab2360f766457416dfc59c6594248c5b79e33c8785bce491c0e01930738f6"
  ],
  ...
}
```

### 3. Get the transaction details
```
bin/xsn-cli getrawtransaction 922ab2360f766457416dfc59c6594248c5b79e33c8785bce491c0e01930738f6 1
error code: -5
error message:
No information available about transaction
```

**Comment by AlexITC** [comment]
if it isn't a transaction, why is it showing this txid `922ab2360f766457416dfc59c6594248c5b79e33c8785bce491c0e01930738f6`?

**Comment by bwang22** [comment]
RPC has new message of `The genesis block coinbase is not considered an ordinary transaction and cannot be retrieved (code -5)`
