### ISSUE TITLE
"getbalance" command actually displays "getreceivedbyaddress"

### ISSUE THREAD

**Issue by drygoatair** [X9Developers/XSN#34]
I added my masternode address as watch-only to my masternode coldwallet. If I use 
`getbalance "mn1" 1 false true` I get the value for `getreceivedbyaddress` instead.

**Comment by AndriiDiachuk** [comment]
Yeah, that`s right, because you have only one address on your account, so value shown for `getbalance "mn1" 1 false true` is similliar  as for `getreceivedbyaddress`.
