### ISSUE TITLE
XSN QT Wallet is banning all the peers

### ISSUE THREAD

**Issue by carlosmmelo** [X9Developers/XSN#4]
Ubuntu 16.04 LTS x64 - XSN QT Version `1.0.0`

I'm not able to syncronize with the network, I realized all peers are banned.

As soon as I unban everyone, it gets in sync.

However this happens again and again.

![image](https://user-images.githubusercontent.com/5649650/37234843-2fc5c704-23c8-11e8-97ff-eae492d97893.png)

**Comment by bwang22** [comment]
Try the new release

**Comment by carlosmmelo** [comment]
@bwang22 its been running for a day with no issues.

:+1: good job.
