### ISSUE TITLE
Add button for flushing mncache

### ISSUE THREAD

**Issue by carlosmmelo** [X9Developers/XSN#45]
Specially for windows user, we often need to delete mncache for wallet to display correct info.

This will require to restart the wallet and start staking from scratch.

It would be good if theres a buttton that we could flush the cache file so that we dont restart the wallet

**Comment by durkmurder** [comment]
We can add this in 1.0.8

**Comment by durkmurder** [comment]
Fixed, will be released in 1.0.9
