### ISSUE TITLE
Masternodes with active seconds < 0

### ISSUE THREAD

**Issue by AlexITC** [X9Developers/XSN#53]
Using the command `masternode list full` is giving values with active seconds < 0, see: ![example](https://media.discordapp.net/attachments/426080585891446784/437490879565922304/masternodes.png)

**Comment by xhiroz** [comment]
@bwang22 I think this was good previously. The negative value is because that node was last seen 17 days and 15 hours ago. You changed this and now it is showing like:

"17d 15h:24m:44s" but "-17d -15h:-24m:-44s" made more sense imo.
