### ISSUE TITLE
Wallet misordering masternodes by active field

### ISSUE THREAD

**Issue by AlexITC** [X9Developers/XSN#54]
While pressing the `active` column twice, I expect the values to be sorted by the `active` field in descending order, this is partially true because it seems to be sorting the rows by the string value instead of the actual time, look to the image, `3d` is before `38d`:
![wallet](https://user-images.githubusercontent.com/4218436/39102078-4a165c70-4666-11e8-97d1-9dfc06d2aa19.png)

**Comment by durkmurder** [comment]
Fixed, will be released in 1.0.9
