### ISSUE TITLE
Masternode tab names needs more space

### ISSUE THREAD

**Issue by carlosmmelo** [X9Developers/XSN#6]
XSN QT Version `1.0.0` - Ubuntu 16.04 x64

When you go to the Masternode tab, Notice in the screenshot below that `My Masternode` and `All Masternode` its not entirely readable. those tabs needs to be a little bit expanded that text will display correctly:

![image](https://user-images.githubusercontent.com/5649650/37238218-dd4417ec-23ef-11e8-8bad-2837df0f15ad.png)

**Comment by AndriiDiachuk** [comment]
Issue was closed in PR#37
