### ISSUE TITLE
Abandoning Transaction Caused Permanently Locked Wallet

### ISSUE THREAD

**Issue by MJbtc** [X9Developers/XSN#76]
**Setup:**
1) Swapped my POSW coins via Livecoin and installed the new XSN wallet on my linux server.
2) Encrypted the wallet and unlocked it.
3) Created new receiving address. Sent coins from Livecoin to address.

**Steps:**
4) Started staking these 17344.67972845 coins. 
5) Sent 2060.5908951 more coins to staking wallet. Initially these appeared fine (see image link A at bottom).
      5a) Wallet starts showing stakes with a "?" next to them in transactions screen (see image link B at
            bottom).
6) A dev on the discord channel, 8489faustn, tells me to abandon the transaction (see image link B at bottom).
      6a) Wallet immediately crashes.
      6b) Restart wallet.  Total correctly shows 19,405.25962355.  But now wallet is locked.
7) Attempt to unlock wallet but it claims my password  is wrong.   I have used this password on this wallet several times before so I know it is correct.

**Result:** Wallet is locked and all of my XSN coins are inaccessible.  Will not accept my password.

**Wallet Version:** 1.0.1 (I believe.  The date below is correct so it was the latest wallet for that date).

**Date:** 3/25/18

**Notes:** 
1) Using an older, decrypted backup of the wallet results in the coins not showing up.  I believe this is because I created the wallet address after I encrypted the wallet.
2) Reinstalling the wallet did nothing.
3) I contacted the dev team for weeks to get this resolved.  John Draper told me to open an issue to have the bug resolved (see image link C at bottom).

**Images:**
A
![a-redacted](https://user-images.githubusercontent.com/39776206/40938889-c07531d4-6808-11e8-8850-53541c3960f5.jpg)
B
![b-redacted](https://user-images.githubusercontent.com/39776206/40938893-c86d759a-6808-11e8-837d-b718adf47b9c.jpg)
C
![c-redactedfixed](https://user-images.githubusercontent.com/39776206/40939103-52b3bc0a-6809-11e8-8fb4-83ca25e19255.jpg)

**Comment by bwang22** [comment]
Please update your wallet. This should no longer be an issue
