### ISSUE TITLE
Corrupted block

### ISSUE THREAD

**Issue by AlexITC** [X9Developers/XSN#78]
The block [95368](https://xsnexplorer.io/blocks/ee5ee42a4f9c106808b8867f9469a47cb7d5fc5f71ec58e56f0bff895ac2b78d) doesn't have a `nextblockhash` field even that we have more than 100k blocks.

**Comment by AlexITC** [comment]
This is another [block](https://xsnexplorer.io/blocks/d8e2c3e4bd1544fee45f3cd88a9a99b39f3632051d8f947d1a5d39e2aee5ecdb) without `nextblockhash`.

**Comment by bwang22** [comment]
Can not reproduce issue. block 95368 has block hash of f7e31f022831fd917acb9291c8db996644bc2c6147e3c776af01327e06a53ae5

getblock f7e31f022831fd917acb9291c8db996644bc2c6147e3c776af01327e06a53ae5 returns
`{
  "hash": "f7e31f022831fd917acb9291c8db996644bc2c6147e3c776af01327e06a53ae5",
  "confirmations": 294187,
  "strippedsize": 479,
  "size": 479,
  "weight": 1916,
  "height": 95368,
  "version": 536870912,
  "versionHex": "20000000",
  "merkleroot": "a95273a8999f5e3b64bf85a8775003081039cc46993b8afa03fc78c204226df2",
  "tx": [
    "e53fe48921630ac969465379cf889e9eea5dcd8e18966c03182ea0b59351f0a2",
    "91b02d72ac5464c12344087878394191f5ee0f80ba9e36248a3fb1392e3e2225"
  ],
  "time": 1526229332,
  "mediantime": 1526229107,
  "nonce": 0,
  "bits": "1c033047",
  "difficulty": 80.28521249766709,
  "chainwork": "00000000000000000000000000000000000000000000000000616e4176ba779c",
  "previousblockhash": "32cb23a129d9edaab1458667ad9bc96c4856b5a8f5aab9d169312efbd8f47efc",
  "nextblockhash": "740c438edddddfe7c4fda54c2ec4cb218f1da1eac5d8db9c792b3a3e4976a3c4"
}`

**Comment by AlexITC** [comment]
This seems to be caused while loading off-chain blocks, thanks.
