### ISSUE TITLE
rpc-commands for blockrewards return different results

### ISSUE THREAD

**Issue by LeeeNux** [X9Developers/XSN#82]
Issue: 

in special cases (don't know exactly when) the results of 2 rpc-commands differ ... but should return the same result (block)

1. xsn-cli masternode winners 5000 | grep -E "receiving address masternode" shows a list of blocks ur node was rewarded for
2. xsn-cli masternodelist lastpaidblock "collateral tx + id used for masternode activation) returns not the last block the node was rewareded for ... but the one before

Expected behavior:

Both commands should return same blocknumber (what i have seen is, that the winnerlist is working correctly (last listentry is last block that was payed)... so i guess there is a bug in "lastpaidblock"-rpc-command in this case

**Comment by bwang22** [comment]
closing issue. Not sure you will get anymore support of this. Comment if you believe this should be reopened
