### ISSUE TITLE
Can`t switch lock-status in listview of coincontrol to release locked coins

### ISSUE THREAD

**Issue by LeeeNux** [X9Developers/XSN#92]
Walletversion: 1.0.13
Binary: xsn-qt (XSN Core Version v1.0.13.0-96f714ff1 (64-Bit))
OS: Ubuntu 18.04 / XFCE / German

Issue:
When trying to switch status of locked collateral coins under Send Coins -> Inputs -> Listview nothing happens.

Expected bahavior:
Locked coins become unlocked, and unlocked coins become locked. This ensures to be able to move collaterals of masternodes or tpos-coins. 

Reproducable: Yes

**Comment by durkmurder** [comment]
Fixed in [PR](https://github.com/X9Developers/XSN/pull/99). Will be included in next release.(1.0.14)
