### ISSUE TITLE
Flush mncache button not workin on 1.0.13

### ISSUE THREAD

**Issue by carlosmmelo** [X9Developers/XSN#93]
When you try `Flush mncache` from wallet repair screen, it seems the command is no longer available after segwit:

![image](https://user-images.githubusercontent.com/5649650/43470308-45622a76-94b6-11e8-8740-b6d840d988ec.png)

**Comment by durkmurder** [comment]
Fixed in [Bugfix/93](https://github.com/X9Developers/XSN/pull/95)
